### ISSUE TITLE
Add a usage guard

### ISSUE THREAD

**Issue by drzax** [abcnews/mount-utils#2]
Currently there's nothing stopping mount points being selected (and used) multiple times (accidentally or otherwise).

I propose that we add a usage guard which excludes mount points from selection if they've been marked as used (and a function for marking points as having been used).

Could using mount points could guard against their own re-use (and potentially re-use after a separate piece of code has used it) but I think it makes most sense to implement this centrally.

Thoughts?

**Comment by colingourlay** [comment]
In addition to this, we should try to guarantee that only one instance of mount-utils is interacting with the mount points, otherwise any usage tracking will be wasted.

Off the top of my head, `Sets` could be used internally to track usage / ownership.
